RailsPryectos/ecommerce/config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                       Controller#Action
#         product_myimages GET    /products/:product_id/myimages(.:format)          myimages#index
#                          POST   /products/:product_id/myimages(.:format)          myimages#create
#      new_product_myimage GET    /products/:product_id/myimages/new(.:format)      myimages#new
#     edit_product_myimage GET    /products/:product_id/myimages/:id/edit(.:format) myimages#edit
#          product_myimage GET    /products/:product_id/myimages/:id(.:format)      myimages#show
#                          PATCH  /products/:product_id/myimages/:id(.:format)      myimages#update
#                          PUT    /products/:product_id/myimages/:id(.:format)      myimages#update
#                          DELETE /products/:product_id/myimages/:id(.:format)      myimages#destroy
#                 products GET    /products(.:format)                               products#index
#                          POST   /products(.:format)                               products#create
#              new_product GET    /products/new(.:format)                           products#new
#             edit_product GET    /products/:id/edit(.:format)                      products#edit
#                  product GET    /products/:id(.:format)                           products#show
#                          PATCH  /products/:id(.:format)                           products#update
#                          PUT    /products/:id(.:format)                           products#update
#                          DELETE /products/:id(.:format)                           products#destroy
#               categories GET    /categories(.:format)                             categories#index
#                          POST   /categories(.:format)                             categories#create
#             new_category GET    /categories/new(.:format)                         categories#new
#            edit_category GET    /categories/:id/edit(.:format)                    categories#edit
#                 category GET    /categories/:id(.:format)                         categories#show
#                          PATCH  /categories/:id(.:format)                         categories#update
#                          PUT    /categories/:id(.:format)                         categories#update
#                          DELETE /categories/:id(.:format)                         categories#destroy
#         new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                          PUT    /users/password(.:format)                         devise/passwords#update
#                          POST   /users/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                           devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                          devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                             devise/registrations#edit
#        user_registration PATCH  /users(.:format)                                  devise/registrations#update
#                          PUT    /users(.:format)                                  devise/registrations#update
#                          DELETE /users(.:format)                                  devise/registrations#destroy
#                          POST   /users(.:format)                                  devise/registrations#create
#           home_purchases GET    /home/purchases(.:format)                         home#purchases
#             home_history GET    /home/history(.:format)                           home#history
#           home_favorites GET    /home/favorites(.:format)                         home#favorites
#               home_index GET    /home/index(.:format)                             home#index
#       home_administrador GET    /home/administrador(.:format)                     home#administrador
#          home_reputation GET    /home/reputation(.:format)                        home#reputation
#            home_products GET    /home/products(.:format)                          home#products
#               home_sales GET    /home/sales(.:format)                             home#sales
#             home_summary GET    /home/summary(.:format)                           home#summary
#                     root GET    /                                                 home#index

Rails.application.routes.draw do
  resources :products do
    resources :myimages
  end
  resources :categories
  devise_for :users

  resources :my_shopping_carts, only: [:create,:destroy]
  resources :favorites, only: [:create,:destroy]
  resources :payments, only: [:show]
  post "/pay", to: "payments#create"
  get "/checkout", to: "payments#checkout"


  get "/add/:product_id", as: :add_to_cart, to: "my_shopping_carts#create" 

  get 'home/search'
  get 'home/car'
  get 'home/purchases'
  get 'home/history'
  get 'home/favorites'
  get 'home/index'
  get 'home/administrador'
  get 'home/reputation'
  get 'home/products'
  get 'home/sales'
  get 'home/summary'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

RailsPryectos/ecommerce/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: :index
  def search
    @products = Product.where("p_name LIKE :query", query: "%#{params[:find]}%")
  end
  def index
    @products = Product.paginate(:page => params[:page], :per_page => 20)
  end

  def purchases
    @payments = current_user.my_payments
  end

  def history
  end

  def favorites
    @favorites = current_user.favorites
  end
  def car
    
  end
end

RailsPryectos/ecommerce/app/helpers/home_helper.rb
module HomeHelper
  def my_cart_model
    raise "ok"
  end
end

RailsPryectos/ecommerce/app/views/home/_panel.html.haml
.col-md-3
  .card
    .card-body
      %ul.nav.nav-pills.flex-column.my-2
        - if current_user.is_admin?
          %li.nav-item
            =link_to "Administrador", home_administrador_path, class:"nav-link"
        %li.nav-item
          =link_to "Resumen", home_summary_path, class:"nav-link"
        %li.nav-item
          =link_to "Reputación", home_reputation_path, class:"nav-link"
        %li.nav-item
          =link_to "Compras", home_purchases_path, class:"nav-link"
        %li.nav-item
          =link_to "Productos", home_products_path, class:"nav-link"
        %li.nav-item
          =link_to "Ventas", home_sales_path, class:"nav-link"
        %li.nav-item
        = link_to "Configuración",  edit_user_registration_path,class:"nav-link"

RailsPryectos/ecommerce/app/views/home/administrador.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            .row
              .col-md-3
                = link_to "Categorias", categories_path, class:"btn btn-primary btn-block"
              .col-md-3
                = link_to "Nueva categoria", new_category_path, class:"btn btn-primary btn-block"
              .col-md-3
                = link_to "Productos", products_path, class:"btn btn-primary btn-block"
              .col-md-3
                = link_to "Nuevo producto", new_product_path, class:"btn btn-primary btn-block"

RailsPryectos/ecommerce/app/views/home/car.html.haml
.py-5
  .container
    .row
      .col-md-12
        .card.large-padding
          .card-body
            .table-responsive
              %table.table.table-striped.table-hover.medium#table_shopping_cart
                %thead
                  %td Producto
                  %td Costo
                  %td Unidades
                  %td Acciones
                %tbody{id: "my_cart", cart_id: "#{@shopping_cart.id}"}
                  -@shopping_cart.in_cart.each do |product|
                    %tr{id: "p_#{product[:id]}"}
                      %td= product[:name]
                      %td= product[:price]
                      %td= product[:quantity]
                      %td
                        %a.btn.btn-danger{:product => "#{product[:id]}", :onclick => "actions.deleteItem(this,#{product[:id]})"}
                          Eliminar
            .top-space.large-padding.text-center#payment_form
              %p{:style => "text-align: right;margin-right:100px;" }
                Total: 
                %strong.medium#mycartTotal  
                  =@shopping_cart.total
            .top-space
              - if @shopping_cart.total > 0
                =render "payments/buttons"

RailsPryectos/ecommerce/app/views/home/favorites.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            %h3.mb-2.text-center Productos
            .table-responsive
              %table.table.table-hover
                %tbody
                  -@favorites.each do |favorite|
                    %tr{:id => "p_#{favorite.id}"}
                      %td.justify-content-between.align-items-center
                        =favorite.product.p_name
                      %td
                        %span.badge.badge-pill.badge-primary.px-3.py-2{ product:"#{favorite.product.id}", class:"", :onclick => "actions.addCart(this)",:id => "c_#{favorite.id}"}
                          %i.fa.fa-fw.fa-shopping-cart.fa-lg
                      %td
                        %span.badge.badge-pill.badge-primary.px-3.py-2{ product:"#{favorite.product.id}", class:"", :onclick => "actions.deleteFavorite(this,#{favorite.id})",:id => "f_#{favorite.id}"}
                          %i.fa.fa-fw.fa-star.fa-lg

RailsPryectos/ecommerce/app/views/home/history.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            %h3.mb-2.text-center Productos
            %ul.list-group
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Disponibles
                %span.badge.badge-pill.badge-primary 4
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Agotados
                %span.badge.badge-primary.badge-pill 2
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Vendidos
                %span.badge.badge-primary.badge-pill 1

RailsPryectos/ecommerce/app/views/home/index.html.haml
.py-5
  .container-fluid
    %p#ejemplo
    %p.ejemplo
    %p.ejemplo
    .row
      -@products.each do |product|
        .col-md-3.col-lg-2.col-sm-12.my-1
          .card
            - if !product.myimages.first.nil?
              =image_tag product.myimages.first.img, class:"card-img-top", style:"max-height:200px"
            .card-body
              .row 
                .col-xs-12col-md-4.col-lg-12
                  %h5.text-center.card-title= product.p_name
                .col-xs-12col-md-8.col-lg-11.col-lg-offset-1
                  =link_to product, class:"btn btn-primary mx-1" do 
                    %i.fa.fa-fw.fa-eye.fa-lg
                  =render "partials/buttons",product:product
    .flickr_pagination
      = will_paginate @products

RailsPryectos/ecommerce/app/views/home/products.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            %h3.mb-2.text-center Productos
            %ul.list-group
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Disponibles
                %span.badge.badge-pill.badge-primary 4
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Agotados
                %span.badge.badge-primary.badge-pill 2
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Vendidos
                %span.badge.badge-primary.badge-pill 1

RailsPryectos/ecommerce/app/views/home/purchases.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            %h3.mb-2.text-center Productos
            %ul.list-group
              - @payments.each do |pay|
                %li.list-group-item.d-flex.justify-content-between.align-items-center
                  %p="Compra #{pay.paypal_id}"
                  =link_to "Ver más",payment_path(pay),class:"btn btn-warning"

RailsPryectos/ecommerce/app/views/home/reputation.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            %h3.mb-2.text-center Productos
            %ul.list-group
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Disponibles
                %span.badge.badge-pill.badge-primary 4
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Agotados
                %span.badge.badge-primary.badge-pill 2
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Vendidos
                %span.badge.badge-primary.badge-pill 1

RailsPryectos/ecommerce/app/views/home/sales.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            %h3.mb-2.text-center Productos
            %ul.list-group
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Disponibles
                %span.badge.badge-pill.badge-primary 4
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Agotados
                %span.badge.badge-primary.badge-pill 2
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Vendidos
                %span.badge.badge-primary.badge-pill 1

RailsPryectos/ecommerce/app/views/home/search.html.haml
.row
  - if !@products.empty?
    -@products.each do |product|
      .col-12.col-sm-4
        .card.my-2
          .card-body
            .row
              .col-8.col-sm-4
                %h4=product.p_name
              .col-4.col-sm-8
                - if !product.myimages.first.nil?
                  =image_tag product.myimages.first.img.url, class:"img-fluid"

  -else
    .card
      .card-body
        %h1.text-center No existen coincidencias

RailsPryectos/ecommerce/app/views/home/summary.html.haml
.py-5
  .container
    .row
      =render "home/panel"
      .col-md-9
        .card.p-2
          .card-body
            %h1.mb-3.text-center.text-capitalize= params[:action]
            %h3.mb-2.text-center Productos
            %ul.list-group
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Disponibles
                %span.badge.badge-pill.badge-primary 4
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Agotados
                %span.badge.badge-primary.badge-pill 2
              %li.list-group-item.d-flex.justify-content-between.align-items-center
                Vendidos
                %span.badge.badge-primary.badge-pill 1