RailsPryectos/ecommerce/config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                       Controller#Action
#         product_myimages GET    /products/:product_id/myimages(.:format)          myimages#index
#                          POST   /products/:product_id/myimages(.:format)          myimages#create
#      new_product_myimage GET    /products/:product_id/myimages/new(.:format)      myimages#new
#     edit_product_myimage GET    /products/:product_id/myimages/:id/edit(.:format) myimages#edit
#          product_myimage GET    /products/:product_id/myimages/:id(.:format)      myimages#show
#                          PATCH  /products/:product_id/myimages/:id(.:format)      myimages#update
#                          PUT    /products/:product_id/myimages/:id(.:format)      myimages#update
#                          DELETE /products/:product_id/myimages/:id(.:format)      myimages#destroy
#                 products GET    /products(.:format)                               products#index
#                          POST   /products(.:format)                               products#create
#              new_product GET    /products/new(.:format)                           products#new
#             edit_product GET    /products/:id/edit(.:format)                      products#edit
#                  product GET    /products/:id(.:format)                           products#show
#                          PATCH  /products/:id(.:format)                           products#update
#                          PUT    /products/:id(.:format)                           products#update
#                          DELETE /products/:id(.:format)                           products#destroy
#               categories GET    /categories(.:format)                             categories#index
#                          POST   /categories(.:format)                             categories#create
#             new_category GET    /categories/new(.:format)                         categories#new
#            edit_category GET    /categories/:id/edit(.:format)                    categories#edit
#                 category GET    /categories/:id(.:format)                         categories#show
#                          PATCH  /categories/:id(.:format)                         categories#update
#                          PUT    /categories/:id(.:format)                         categories#update
#                          DELETE /categories/:id(.:format)                         categories#destroy
#         new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                          PUT    /users/password(.:format)                         devise/passwords#update
#                          POST   /users/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                           devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                          devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                             devise/registrations#edit
#        user_registration PATCH  /users(.:format)                                  devise/registrations#update
#                          PUT    /users(.:format)                                  devise/registrations#update
#                          DELETE /users(.:format)                                  devise/registrations#destroy
#                          POST   /users(.:format)                                  devise/registrations#create
#           home_purchases GET    /home/purchases(.:format)                         home#purchases
#             home_history GET    /home/history(.:format)                           home#history
#           home_favorites GET    /home/favorites(.:format)                         home#favorites
#               home_index GET    /home/index(.:format)                             home#index
#       home_administrador GET    /home/administrador(.:format)                     home#administrador
#          home_reputation GET    /home/reputation(.:format)                        home#reputation
#            home_products GET    /home/products(.:format)                          home#products
#               home_sales GET    /home/sales(.:format)                             home#sales
#             home_summary GET    /home/summary(.:format)                           home#summary
#                     root GET    /                                                 home#index

Rails.application.routes.draw do
  resources :products do
    resources :myimages
  end
  resources :categories
  devise_for :users

  resources :my_shopping_carts, only: [:create,:destroy]
  resources :favorites, only: [:create,:destroy]
  resources :payments, only: [:show]
  post "/pay", to: "payments#create"
  get "/checkout", to: "payments#checkout"


  get "/add/:product_id", as: :add_to_cart, to: "my_shopping_carts#create" 

  get 'home/search'
  get 'home/car'
  get 'home/purchases'
  get 'home/history'
  get 'home/favorites'
  get 'home/index'
  get 'home/administrador'
  get 'home/reputation'
  get 'home/products'
  get 'home/sales'
  get 'home/summary'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

RailsPryectos/ecommerce/app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id            :integer          not null, primary key
#  p_available   :boolean
#  p_description :text
#  p_name        :string
#  p_price       :float
#  p_quantify    :integer
#  p_send        :float
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  user_id       :integer
#
# Indexes
#
#  index_products_on_user_id  (user_id)
#

class Product < ApplicationRecord
  belongs_to :user
  has_many :myimages, :dependent => :destroy
  has_many :has_categories, :dependent => :destroy
  has_many :categories, through: :has_categories, :dependent => :destroy
  after_create :save_categories
  validate :valide_categories

  #Validates
  validates :p_name, presence: true, length: {minimum: 10, too_short: "Minimo son %{count} caracteres." }
  validates :p_description, presence: true, length: {minimum: 50, too_short: "Minimo son %{count} caracteres." }
  validates :p_price, presence: true, :numericality => true
  validates :p_send, presence: true, :numericality => true

  def categories=(value)
  	@categories = value
  end
  def getCategories
		@categories
  end  
  def paypal_form
  	{id: id, name: p_name, sku: :item, price: (p_price / 100), currency:"USD", quantity: 1 }
  end
  private
  def save_categories
  	@categories.each do |category_id|
  		HasCategory.create(category_id: category_id, product_id: self.id)
  	end
  end
  def valide_categories
  	if self.getCategories.blank? && self.id.nil?
  		errors.add(:categories, "Debe agregar una categoria.")
  	end
  end
end

RailsPryectos/ecommerce/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(product_params)
    @product.categories = params[:categories]
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:p_name, :p_description, :p_price, :p_quantify, :p_send, :p_available)
    end
end

RailsPryectos/ecommerce/app/helpers/products_helper.rb
module ProductsHelper
end

RailsPryectos/ecommerce/app/views/products/_buttons.html.haml
- if can? :update, img
  =link_to "Edit", edit_product_myimage_path(@product,img),class:"btn btn-success btn-block"
- if can? :delete, img
  = link_to 'Destroy', [@product,img], method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger btn-block"
%h1=img.title
%p=truncate(img.description, length:600)

RailsPryectos/ecommerce/app/views/products/_form.html.haml
.container.py-5
  .row
    .col-md-12 
      .card
        .card-body
          %h1.text-center.my-5= title ||= "Titulo"
          = form_for @product, builder: BootstrapFormBuilder  do |f|
            .row 
              = f.errors
              = f.label :name
              = f.text_field :p_name
              = f.label :description
              = f.text_area :p_description
              = f.label :price
              = f.text_field :p_price
              = f.label :quantify
              = f.number_field :p_quantify
              = f.label :send
              = f.text_field :p_send
              = f.label :available
              = f.check_box :p_available
              - Category.all.each do |category|
                .col-md-4.my-5
                  = check_box_tag "categories[]", category.id
                  = category.name
            .row
              .offset-md-2
              = f.submit 'Save'
              .col-md-4
                = link_to "Atrás", home_administrador_path, class: "btn btn-secondary btn-block"

RailsPryectos/ecommerce/app/views/products/edit.html.haml
= render 'form',title:"Editing product"

RailsPryectos/ecommerce/app/views/products/index.html.haml
.container.py-5
  .row
    .col-md-12 
      .card
        .card-body
          %h1.text-center.my-5= title ||= "Titulo"

          %h1 Listing products

          %table.table
            %thead
              %tr
                %th name
                %th description
                %th price
                %th quantify
                %th send
                %th available
                %th User
                %th
                %th
                %th

            %tbody
              - @products.each do |product|
                %tr
                  %td= product.p_name
                  %td= truncate(product.p_description,length:50)
                  %td= product.p_price
                  %td= product.p_quantify
                  %td= product.p_send
                  %td= product.p_available
                  %td= product.user.name
                  %td= link_to 'Show', product
                  %td= link_to 'Add image', new_product_myimage_path(product)
                  %td= link_to 'Edit', edit_product_path(product)
                  %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }

          %br

          = link_to 'New Product', new_product_path
          .flickr_pagination
            = will_paginate @products

RailsPryectos/ecommerce/app/views/products/new.html.haml
= render 'form',title:"New product"

RailsPryectos/ecommerce/app/views/products/show.html.haml
.container-fluid
  .card.shadonw-5.my-5
    .card-body
      .row
        .col-md-8
          %h1.text-center= @product.p_name
          - if can? :edit, @product
            .my-3
              = link_to 'Edit', edit_product_path(@product),class:"btn btn-primary btn-block"
              = link_to 'Add image', new_product_myimage_path(@product),class:"btn btn-secondary btn-block"
          %p= @product.p_description
          %p= "Costo: #{@product.p_price}"
          %p= "En stock: #{@product.p_quantify}"
          %p= "Costo envio: #{@product.p_send}"
          %p= "Disponible: #{@product.p_available}"
          %p.text-right
            =render "partials/buttons",product: @product
        .col-md-4
          .row
            .col-12
              #carouselExampleIndicators.carousel.slide{"data-ride" => "carousel"}
                %ul.carousel-indicators
                  - flag = false
                  - cont = 0
                  - @product.myimages.ids.each do |con|
                    - if flag
                      %li{"data-slide-to" => "#{cont}", "data-target" => "#carouselExampleIndicators"}
                    - else  
                      %li.active{"data-slide-to" => "#{cont}", "data-target" => "#carouselExampleIndicators"}
                      - flag = true
                    - cont = cont + 1
                .carousel-inner
                  - flag = false
                  -@product.myimages.each do |image|
                    - if flag  
                      .carousel-item
                        = image_tag image.img.url(:big),class:"d-block w-100  img-fluid"
                        .carousel-caption
                          =render "buttons",img:image
                    - else
                      .carousel-item.active
                        = image_tag image.img.url(:big),class:"d-block w-100   img-fluid"
                        - flag = true
                        .carousel-caption
                          =render "buttons",img:image
                %a.carousel-control-prev{"data-slide" => "prev", :href => "#carouselExampleIndicators", :role => "button"}
                  %span.carousel-control-prev-icon{"aria-hidden" => "true"}
                  %span.sr-only Previous
                %a.carousel-control-next{"data-slide" => "next", :href => "#carouselExampleIndicators", :role => "button"}
                  %span.carousel-control-next-icon{"aria-hidden" => "true"}
                  %span.sr-only Next
        