RailsPryectos/ecommerce/config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                       Controller#Action
#         product_myimages GET    /products/:product_id/myimages(.:format)          myimages#index
#                          POST   /products/:product_id/myimages(.:format)          myimages#create
#      new_product_myimage GET    /products/:product_id/myimages/new(.:format)      myimages#new
#     edit_product_myimage GET    /products/:product_id/myimages/:id/edit(.:format) myimages#edit
#          product_myimage GET    /products/:product_id/myimages/:id(.:format)      myimages#show
#                          PATCH  /products/:product_id/myimages/:id(.:format)      myimages#update
#                          PUT    /products/:product_id/myimages/:id(.:format)      myimages#update
#                          DELETE /products/:product_id/myimages/:id(.:format)      myimages#destroy
#                 products GET    /products(.:format)                               products#index
#                          POST   /products(.:format)                               products#create
#              new_product GET    /products/new(.:format)                           products#new
#             edit_product GET    /products/:id/edit(.:format)                      products#edit
#                  product GET    /products/:id(.:format)                           products#show
#                          PATCH  /products/:id(.:format)                           products#update
#                          PUT    /products/:id(.:format)                           products#update
#                          DELETE /products/:id(.:format)                           products#destroy
#               categories GET    /categories(.:format)                             categories#index
#                          POST   /categories(.:format)                             categories#create
#             new_category GET    /categories/new(.:format)                         categories#new
#            edit_category GET    /categories/:id/edit(.:format)                    categories#edit
#                 category GET    /categories/:id(.:format)                         categories#show
#                          PATCH  /categories/:id(.:format)                         categories#update
#                          PUT    /categories/:id(.:format)                         categories#update
#                          DELETE /categories/:id(.:format)                         categories#destroy
#         new_user_session GET    /users/sign_in(.:format)                          devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                          devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                         devise/sessions#destroy
#        new_user_password GET    /users/password/new(.:format)                     devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                    devise/passwords#edit
#            user_password PATCH  /users/password(.:format)                         devise/passwords#update
#                          PUT    /users/password(.:format)                         devise/passwords#update
#                          POST   /users/password(.:format)                         devise/passwords#create
# cancel_user_registration GET    /users/cancel(.:format)                           devise/registrations#cancel
#    new_user_registration GET    /users/sign_up(.:format)                          devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                             devise/registrations#edit
#        user_registration PATCH  /users(.:format)                                  devise/registrations#update
#                          PUT    /users(.:format)                                  devise/registrations#update
#                          DELETE /users(.:format)                                  devise/registrations#destroy
#                          POST   /users(.:format)                                  devise/registrations#create
#           home_purchases GET    /home/purchases(.:format)                         home#purchases
#             home_history GET    /home/history(.:format)                           home#history
#           home_favorites GET    /home/favorites(.:format)                         home#favorites
#               home_index GET    /home/index(.:format)                             home#index
#       home_administrador GET    /home/administrador(.:format)                     home#administrador
#          home_reputation GET    /home/reputation(.:format)                        home#reputation
#            home_products GET    /home/products(.:format)                          home#products
#               home_sales GET    /home/sales(.:format)                             home#sales
#             home_summary GET    /home/summary(.:format)                           home#summary
#                     root GET    /                                                 home#index

Rails.application.routes.draw do
  resources :products do
    resources :myimages
  end
  resources :categories
  devise_for :users

  resources :my_shopping_carts, only: [:create,:destroy]
  resources :favorites, only: [:create,:destroy]
  resources :payments, only: [:show]
  post "/pay", to: "payments#create"
  get "/checkout", to: "payments#checkout"


  get "/add/:product_id", as: :add_to_cart, to: "my_shopping_carts#create" 

  get 'home/search'
  get 'home/car'
  get 'home/purchases'
  get 'home/history'
  get 'home/favorites'
  get 'home/index'
  get 'home/administrador'
  get 'home/reputation'
  get 'home/products'
  get 'home/sales'
  get 'home/summary'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

RailsPryectos/ecommerce/app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id                 :integer          not null, primary key
#  c_img_content_type :string
#  c_img_file_name    :string
#  c_img_file_size    :integer
#  c_img_updated_at   :datetime
#  description        :string
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Category < ApplicationRecord
    has_attached_file :c_img,
        styles: {
            thumb:   { geometry: '500x500>' ,     format: :png, convert_options: " -background white -gravity center -extent 500x500"},
            medium:  { geometry: '630x315>' ,    format: :png, convert_options: " -background white -gravity center -extent 630x315"},
            big:     { geometry: '920x560>' ,    format: :png, convert_options: " -background white -gravity center -extent 920x560"},
            }, 
            default_url: "/images/:style/missing.png"
    validates_attachment_content_type :c_img, content_type: /\Aimage\/.*\z/
    validates :name, presence: true, length: {minimum: 10, too_short: "Minimo son %{count} caracteres." }
    validates :description, presence: true, length: {minimum: 50, too_short: "Minimo son %{count} caracteres." }
  has_many :has_categories, :dependent => :destroy
  has_many :products, through: :has_categories, :dependent => :destroy
end

RailsPryectos/ecommerce/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  #before_action :set_category, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products.paginate(:page => params[:page], :per_page => 12)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description, :c_img)
    end
end

RailsPryectos/ecommerce/app/helpers/categories_helper.rb
module CategoriesHelper
end

RailsPryectos/ecommerce/app/views/categories/_form.html.haml
.container.py-5
  .row
    .col-md-12 
      .card
        .card-body
          %h1.text-center.my-5= title ||= "Titulo"
          = form_for @category, builder: BootstrapFormBuilder do |f|
            .row
              = f.errors
              = f.label :name
              = f.text_field :name,placeholder: "Minimo 7 caracteres"
              = f.label :description
              = f.text_area :description, placeholder:"Minimo 10 caracteres"
              = f.label :Imagen
              = f.file_field :c_img
              .col-md-2
              = f.submit "Enviar"
              .col-md-4
                = link_to "Atrás", home_administrador_path,class:"btn btn-secondary btn-block"

RailsPryectos/ecommerce/app/views/categories/edit.html.haml
= render 'form',title:"Editar Categoria"

RailsPryectos/ecommerce/app/views/categories/index.html.haml
.container.py-5
  .row
    .col-md-12
      .card
        .card-body
          .row
            .col-12
              %h1.text-center Listing categories
            .offset-md-3.col-md-3.my-4
              = link_to 'New Category', new_category_path,class:"btn btn-block btn-primary"
            .col-md-3.my-4
              = link_to 'Atrás', home_administrador_path,class:"btn btn-block btn-primary"
            .col-md-12.table-responsive
              %table.table
                %thead
                  %tr
                    %th Name
                    %th Description
                    %th C img
                    %th
                    %th
                    %th
                %tbody
                  - @categories.each do |category|
                    %tr
                      %td= category.name
                      %td=truncate(category.description,length:600)
                      %td= category.c_img
                      %td= link_to 'Show', category,class:"btn btn-block btn-primary"
                      %td= link_to 'Edit', edit_category_path(category),class:"btn btn-block btn-primary"
                      %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-block btn-primary"

RailsPryectos/ecommerce/app/views/categories/new.html.haml
= render 'form',title:"Nueva Categoria"

RailsPryectos/ecommerce/app/views/categories/show.html.haml
.container.my-5
  .row
    .col-12
      .card
        .card-body
          .row
            .col-9
              .row
                .col-12
                  %h1.text-center= @category.name
                - if can? :update, @category
                  .offset-md-3.col-md-3
                    = link_to 'Edit', edit_category_path(@category),class:"btn btn-primary btn-block"
                  .col-md-3
                    = link_to 'Back', categories_path,class:"btn btn-secondary btn-block"
                .col-12
                  %p.my-2= @category.description
            .col-3
              =image_tag @category.c_img, class: "img-fluid"
  .row
    -@products.each do |product|
      .col-md-4.my-5
        .card.h-100
          .card-body
            %h4=product.p_name
            %p=truncate(product.p_description,length:150)
            .text-right
              =link_to "Show",product,class:"btn btn-info my-3"
              -if can? :update, product
                =link_to "Editar",edit_product_path(product),class:"btn btn-info my-3"
  .flickr_pagination
    = will_paginate @products